theme: minima
title: GrooveForge Docs
description: Documentation for the GrooveForge app
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
# For GitHub project pages: https://<user>.github.io/<repo>/
baseurl: "/groove-forge"
url: "https://mmnastase.github.io"
permalink: pretty
nav:
  - title: Home
    url: /
  - title: User Guide
    url: /user-guide
  - title: Builder
    url: /builder
  - title: Widgets
    url: /widgets/
  - title: Releases
    url: /releases

